### ISSUE TITLE
Extreme-hobby Store

### ISSUE THREAD

**Issue by orenshim** [j26design/Ecwid-Premium#32] opened 2016-08-14 08:10 UTC
Dear John,

My name is Oren from Israel, I am a graphic designer and I'm building a website for my client. I use the widget of Ecwid and I came across some problems.

1. I've created menu navigation and menu widget does not take into relevant category, however, the menu always brings the main category of the store, no matter which button you click. How can I fix this?

2. I added the possibility to introduce additional products. The title appears in English. How do I change the title into Hebrew?

3. Also, as shown in additional products, the arrows are directed inward instead of outward, how can fix it?

4. Log in button appears on the text form. (Attached screenshot) how can I fix it?

5. I need to create spacing between words in the gray panel appears on the right. For example, via Allenby: Speed 26 cc (attached screenshot)

**Attached screenshots and a link to the site:
![order form](https://cloud.githubusercontent.com/assets/20366453/17647994/943926a8-620f-11e6-8da5-0b9715f169a0.jpg)
![you may also like options](https://cloud.githubusercontent.com/assets/20366453/17647995/98163b44-620f-11e6-868e-0d2110a248a1.png)
![gray panel](https://cloud.githubusercontent.com/assets/20366453/17647996/9b95a0b6-620f-11e6-941d-634808a5b56a.jpg)

**
http://xtreme-hobbyracing.businesscatalyst.com/index.html

**Comment by jp26jp** [comment] 2016-09-04 04:18
[Duplicate of this issue](https://github.com/j26design/Ecwid-Premium/issues/34)

**Closed by jp26jp** 2016-09-04 04:18 UTC
Labels: duplicate
