### ISSUE TITLE
Ecwid Product info layout w/tables

### ISSUE THREAD

**Issue by Pogonotrophics** [j26design/Ecwid-Premium#23] opened 2016-07-15 20:31 UTC
I have been working on using tables for my product information to create a more consistent layout as well as give more information with the first viewing of the page for that product (without scrolling). I have insured that the table layout aligns everything to the left. When testing this with the widgets most cells are aligning center, although some are retaining the Left alignment. I have created a new page to test using the newest version of your Ecwid ecommerce widgets and seeing the same results.

Also, with the newest Navigation I am noticing that the text font points are not changing when viewing the page - they are stuck at the default setting despite changing it.

**Comment by jp26jp** [comment] 2016-07-16 07:40
> When testing this with the widgets most cells are aligning center, although some are retaining the Left alignment

I'm not able to reproduce this. The widget doesn't contain any settings that would influence the text alignment of the tables inside of the description. Can you upload the Muse file [here](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN)?

> The text font points are not changing when viewing the page - they are stuck at the default setting.

I'm also not able to reproduce this. Please upload the Muse file [here](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN)

**Comment by jp26jp** [comment] 2016-07-17 20:35
Okay, I got your upload. Where can I find a product with a table?

**Comment by jp26jp** [comment] 2016-07-21 02:46
Okay, well since I can't reproduce this, and there isn't a link to show the product, I'm going to close this issue. But once you have a product up, feel free to reopen the issue and paste the link so I can see what's going on.

**Comment by Pogonotrophics** [comment] 2016-07-21 02:56
I sent you the link. Please review received email. I will resend since it is obvious you don't check you email.
On Jul 20, 2016 9:46 PM, John R Perry <notifications@github.com> wrote:Okay, well since I can't reproduce this, and there isn't a link to show the product, I'm going to close this issue. But once you have a product up, feel free to reopen the issue and paste the link so I can see what's going on.

**Comment by Pogonotrophics** [comment] 2016-07-21 02:58
John,

 

I have uploaded the file that is currently published. I do not have the file published that uses the newest version of the widgets, yet was showing the same glitch when viewed within the browser. Of note, the glitch does not show in Muse preview mode.

 

To test use this link to the actual item within my store that I have set up for testing. http://www.pogonotrophics.com/store.html#!/DISCONTINUED-All-Natural-BEARD-BUTTER-120ml/p/46835143/category=12170277

 

Also of note, this item is no longer in stock yet it shows as being in stock and is allowing it to be added to the cart. I am reset this SKU to ensure it was 0 stock and still shows in stock.

**Comment by jp26jp** [comment] 2016-07-21 04:37
Post it here. There's no reason to split the conversation between mediums.

**Comment by jp26jp** [comment] 2016-07-21 15:53
Okay, I see the issue. I'll add this to the next update but for now, add this to the `<head>` of your master pages and it will fix the bug:

    <style>
    html#ecwid_html body#ecwid_body .ecwid td[align="left"] [itemprop="description"] td[align="left"] {
      text-align:left!important;
    }
    html#ecwid_html body#ecwid_body .ecwid td[align="right"] [itemprop="description"] td[align="right"] {
      text-align:right!important;
    }
    </style>

**Comment by jp26jp** [comment] 2016-07-25 04:05
This was fixed in _Storefront V8.17.11_

**Closed by jp26jp** 2016-07-25 04:05 UTC
Labels: bug
