### ISSUE TITLE
bugs in Ecwid

### ISSUE THREAD

**Issue by orenshim** [j26design/Ecwid-Premium#37] opened 2016-09-11 17:28 UTC
Hi John,
Here are another two bugs I found, I've provided you file.
Thank you, you help me a lot!
![bugs2](https://cloud.githubusercontent.com/assets/20366453/18419205/2c3a3988-785e-11e6-9e56-ca2a04f3d3b5.jpg)
![bugs](https://cloud.githubusercontent.com/assets/20366453/18419206/2c67950e-785e-11e6-8b8d-bebedb6d117c.jpg)

http://xtreme-hobbyracing.businesscatalyst.com/%D7%97%D7%A0%D7%95%D7%AA.html#!/%D7%9E%D7%95%D7%A6%D7%A8%D7%99-%D7%A4%D7%A8%D7%99%D7%9E%D7%99%D7%95%D7%9D-%D7%9C%D7%9E%D7%A7%D7%A6%D7%95%D7%A2%D7%A0%D7%99%D7%9D/c/20416013/offset=0&sort=normal

**Comment by jp26jp** [comment] 2016-09-29 03:58
The checkbox seems to be loading on the same line when I look at the website. Was something changed or are you still seeing the issue? I added an update to the widget that will fix the order of the text.

The sentence that is in English is something Ecwid has to fix (unless you are using the 'Text' widget). If you're using the text widget, remove it.

What does the text with the #038& say in English?

What part of the radio button should appear right?

**Comment by orenshim** [comment] 2016-09-29 04:56
Hi John,

First of all, thank you very much.
Attached files to explain the problem

**Comment by jp26jp** [comment] 2016-09-30 06:26
Nothing was attached

**Comment by jp26jp** [comment] 2016-10-15 08:17
[https://github.com/j26design/Ecwid-Premium/issues/34](Duplicate of this issue)

**Closed by jp26jp** 2016-10-15 08:17 UTC
