### ISSUE TITLE
RTL for Hebrew and Arabic

### ISSUE THREAD

**Issue by orenshim** [j26design/Ecwid-Premium#20] opened 2016-07-09 05:58 UTC
Hi,
First of all, thank you for the wonderful widget.
My name is Oren and I am from Israel. I want to build a store in Hebrew.
For that I have to write from right to left. ECWID of the system can be integrated into RTL code.
How this can be done through widget, or whether such an option may be added in the next update of the widget?

Thanks!

**Comment by jp26jp** [comment] 2016-07-09 23:05
I'd definitely love to provide this feature! If Ecwid supports it, the widget should be able to. When you enter your Store ID, is something not working?

**Comment by orenshim** [comment] 2016-07-10 04:26
At the moment it does not work.
Within the store you can add CSS code for RTL

Below is a link I found about it:

https://www.ecwid.com/forums/showthread.php?t=29720

For example a file attachment.

Thanks!

**Comment by jp26jp** [comment] 2016-07-10 17:47
That thread actually says to place the CSS in ecwid's settings. Have you tried adding it there?

**Comment by orenshim** [comment] 2016-07-10 19:44
First, the answer is yes :-)
Second, the code does not work when I use the widget.

Thank you for your patience.

**Comment by jp26jp** [comment] 2016-09-04 04:18
[Duplicate of this issue](https://github.com/j26design/Ecwid-Premium/issues/34)

**Closed by jp26jp** 2016-09-04 04:18 UTC
Labels: enhancement
